---

- name: Create profiles
  hosts: f5-test
  connection: local

  vars:
    provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Create BASE client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ provider }}"
        state: present
        name: TEST_BASE_profile
        ciphers: "TLSv1_2:TLSv1_1"
        cert_key_chain:
          - cert: default.crt
            key: default.key
      delegate_to: localhost

    - name: Create CHILD client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ provider }}"
        state: present
        name: TEST_CHILD_profile
        parent: TEST_BASE_profile
      delegate_to: localhost

